// Auto-generated by scripts/generate-frontend-version.cjs.
// Run "npm --prefix frontend run version:generate" to refresh.

export const APP_VERSION = 'dev-d6a9ac3';

export const APP_BUILD_INFO = {
    version: 'dev-d6a9ac3',
    branch: 'feature/ontology-merge-clean',
    commitHash: 'd6a9ac3',
    commitDate: '2026-04-23 18:20:05 -0600',
    buildDate: '2026-04-24T15:19:18.888Z',
} as const;
