// Auto-generated by scripts/generate-frontend-version.cjs.
// Run "npm --prefix frontend run version:generate" to refresh.

export const APP_VERSION = '0.1.0';

export const APP_BUILD_INFO = {
    version: '0.1.0',
    branch: 'main',
    commitHash: 'b0c775a',
    commitDate: '2026-04-24 09:42:13 -0600',
    buildDate: '2026-04-24T16:32:34.568Z',
} as const;
